### ISSUE TITLE
Invalid VST3 Module Path error

### ISSUE THREAD

**Issue by glitterball** [ardura/Subhoofer#8]
Hi, I get a "Invalid VST3 Module Path: '' error  if I try to install in the $HOME/.vst3/ folder.
If I install to /usr/lib/vst3/Subhoofer.vst3/Contents/x86_64-linux/Subhoofer.so , then it works as expected.

**Comment by ardura** [comment]
Hi glitterball! Are you building Subhoofer manually? I haven't seen this one before but I also am a windows user most of the time. Does this error happen in multiple hosts?

**Comment by glitterball** [comment]
Hi, No I just downloaded the binary.
Normally the directory structure of the plugin would be:
Plugin.vst3/Contents/Plugin.so

However in this case it extracts to Contents/x86_64-linux/Subhoofer.so (without the Subhoofer.vst3)

When  I change the path to $HOME/.vst3/Subhoofer.vst3/Contents/x86_64-linux/Subhoofer.so , it returns the Invalid VST3 Module Path: '' error. 

I haven't tried it in multiple hosts - just Ardour.

**Comment by ardura** [comment]
Can you try with the latest release? I replaced the binary yesterday actually so I wonder if you tried it before that. Maybe that was my fault but it now has that structure:
![image](https://github.com/ardura/Subhoofer/assets/31751444/31bda81a-771d-454c-82d9-73ced91b7b13)
I do see what you mean though:
https://github.com/robbert-vdh/nih-plug/blob/bb274976ca138289436b0bfa209b2c8c13244225/nih_plug_xtask/src/lib.rs#L704

**Comment by glitterball** [comment]
That seems to be fixed now. Thank you!

**Comment by ardura** [comment]
Glad to hear it! Happy producing 😊
